apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k3s-dev-apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/demo-nginx/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
